"""base de datos

Revision ID: 06adacae6d70
Revises: 
Create Date: 2025-08-16 10:09:02.104228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06adacae6d70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('numero_telefono', sa.String(length=10), nullable=False),
    sa.Column('contraseña', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False),
    sa.CheckConstraint("LENGTH(numero_telefono) = 10 AND numero_telefono ~ '^[0-9]+$'", name='check_numero_telefono'),
    sa.CheckConstraint('LENGTH(contraseña) >= 6', name='check_contraseña_admin'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('numero_telefono')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index('idx_admin_cedula', ['cedula'], unique=False)
        batch_op.create_index('idx_admin_numero_telefono', ['numero_telefono'], unique=False)

    op.create_table('busqueda_terminos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('termino', sa.String(length=255), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=False),
    sa.Column('ultima_busqueda', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('termino')
    )
    op.create_table('cart_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_principales',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('contraseña', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False),
    sa.CheckConstraint("LENGTH(numero) = 10 AND numero ~ '^[0-9]+$'", name='check_numero'),
    sa.CheckConstraint('LENGTH(contraseña) >= 6', name='check_contraseña'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('subcategorias',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('categoria_principal_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_principal_id'], ['categorias_principales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.create_index('idx_subcategoria_categoria_principal_id', ['categoria_principal_id'], unique=False)

    op.create_table('seudocategorias',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('subcategoria_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('seudocategorias', schema=None) as batch_op:
        batch_op.create_index('idx_seudocategoria_subcategoria_id', ['subcategoria_id'], unique=False)

    op.create_table('productos',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('imagen_url', sa.String(length=255), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('seudocategoria_id', sa.String(length=36), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False),
    sa.CheckConstraint('precio > 0', name='check_precio_positivo'),
    sa.CheckConstraint('stock >= 0', name='check_stock_no_negativo'),
    sa.ForeignKeyConstraint(['seudocategoria_id'], ['seudocategorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index('idx_producto_estado', ['estado'], unique=False)
        batch_op.create_index('idx_producto_marca', ['marca'], unique=False)
        batch_op.create_index('idx_producto_nombre', ['nombre'], unique=False)
        batch_op.create_index('idx_producto_nombre_lower', [sa.literal_column('lower(nombre)')], unique=False)
        batch_op.create_index('idx_producto_seudocategoria_id', ['seudocategoria_id'], unique=False)

    op.create_table('cart_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index('idx_session_product', ['session_id', 'product_id'], unique=False)
        batch_op.create_index('idx_user_product', ['user_id', 'product_id'], unique=False)

    op.create_table('likes',
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('producto_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'producto_id', name='unique_usuario_producto_like')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index('idx_like_producto_id', ['producto_id'], unique=False)
        batch_op.create_index('idx_like_usuario_id', ['usuario_id'], unique=False)

    op.create_table('reseñas',
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('producto_id', sa.String(length=36), nullable=False),
    sa.Column('texto', sa.String(length=1000), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='estado_enum'), nullable=False),
    sa.CheckConstraint('calificacion >= 1 AND calificacion <= 5', name='check_calificacion_rango'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'producto_id', name='unique_usuario_producto_reseña')
    )
    with op.batch_alter_table('reseñas', schema=None) as batch_op:
        batch_op.create_index('idx_reseña_producto_id', ['producto_id'], unique=False)
        batch_op.create_index('idx_reseña_usuario_id', ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reseñas', schema=None) as batch_op:
        batch_op.drop_index('idx_reseña_usuario_id')
        batch_op.drop_index('idx_reseña_producto_id')

    op.drop_table('reseñas')
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index('idx_like_usuario_id')
        batch_op.drop_index('idx_like_producto_id')

    op.drop_table('likes')
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index('idx_user_product')
        batch_op.drop_index('idx_session_product')

    op.drop_table('cart_items')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index('idx_producto_seudocategoria_id')
        batch_op.drop_index('idx_producto_nombre_lower')
        batch_op.drop_index('idx_producto_nombre')
        batch_op.drop_index('idx_producto_marca')
        batch_op.drop_index('idx_producto_estado')

    op.drop_table('productos')
    with op.batch_alter_table('seudocategorias', schema=None) as batch_op:
        batch_op.drop_index('idx_seudocategoria_subcategoria_id')

    op.drop_table('seudocategorias')
    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.drop_index('idx_subcategoria_categoria_principal_id')

    op.drop_table('subcategorias')
    op.drop_table('usuarios')
    op.drop_table('categorias_principales')
    op.drop_table('cart_sessions')
    op.drop_table('busqueda_terminos')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index('idx_admin_numero_telefono')
        batch_op.drop_index('idx_admin_cedula')

    op.drop_table('admins')
    # ### end Alembic commands ###
