"""agregar tabla busqueda

Revision ID: 2bb9436f1c58
Revises: 1f45fe8d3155
Create Date: 2025-08-03 17:31:01.085149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb9436f1c58'
down_revision = '1f45fe8d3155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busqueda_terminos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('termino', sa.String(length=255), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=True),
    sa.Column('ultima_busqueda', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('termino')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('busqueda_terminos')
    # ### end Alembic commands ###
