"""agregar tabla busqueda

Revision ID: ec8e37f0537c
Revises: 2bb9436f1c58
Create Date: 2025-08-03 17:47:44.309755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8e37f0537c'
down_revision = '2bb9436f1c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index('idx_producto_marca', ['marca'], unique=False)
        batch_op.create_index('idx_producto_nombre_lower', [sa.literal_column('lower(nombre)')], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index('idx_producto_nombre_lower')
        batch_op.drop_index('idx_producto_marca')

    # ### end Alembic commands ###
